/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CustomerController;
import controller.OrderController;
import dto.CustomerDTO;
import dto.ItemDTO;
import dto.OrderDTO;
import dto.OrderDetailDTO;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import entity.Customer;
import entity.Item;
import entity.Order;
import entity.OrderDetail;

/**
 *
 * @author Sahan
 */
public class OrderForm extends javax.swing.JFrame {

    DefaultTableModel dtm;

    /**
     * Creates new form OrderForm
     */
    public OrderForm() {
        initComponents();
        loadAllItems();
        setDate();
        dtm = (DefaultTableModel) tblOrders.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtODate = new javax.swing.JTextField();
        txtOID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmbItem = new javax.swing.JComboBox<String>();
        txtItemQtyOnHand = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        txtItemCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCusName = new javax.swing.JTextField();
        txtCusAddress = new javax.swing.JTextField();
        txtSearcCusNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtBuyQty = new javax.swing.JTextField();
        btnAddTable = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        btnPurhchaseOrder = new javax.swing.JButton();
        lblGrandTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Order Manage");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtODate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 20));
        jPanel2.add(txtOID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 20));

        jLabel2.setText("Order Date");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel4.setText("Order ID");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 350, 70));

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbItem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbItemItemStateChanged(evt);
            }
        });
        jPanel3.add(cmbItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, -1));
        jPanel3.add(txtItemQtyOnHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, -1));
        jPanel3.add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, -1));
        jPanel3.add(txtItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, -1));
        jPanel3.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 130, -1));

        jLabel11.setText("Select Item");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel13.setText("Item Code");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel14.setText("Item Name");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel15.setText("Item Qty on Hand");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel16.setText("Item Unit Price");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 340, 170));

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCusNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 20));
        jPanel4.add(txtCusAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 130, 20));

        txtSearcCusNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearcCusNoActionPerformed(evt);
            }
        });
        jPanel4.add(txtSearcCusNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 20));

        jLabel3.setText("Search from Number");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, -1));

        jLabel8.setText("Customer Name");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel9.setText("Customer Address");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 130, 20));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 350, 150));

        jPanel7.setBackground(new java.awt.Color(254, 254, 254));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(txtBuyQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 120, 20));

        btnAddTable.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnAddTable.setText("Add to Cart");
        btnAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTableActionPerformed(evt);
            }
        });
        jPanel7.add(btnAddTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 120, 20));

        jLabel5.setText("Buy Qty");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 340, 70));

        jPanel6.setBackground(new java.awt.Color(254, 254, 254));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemCode", "Item Name", "Qty", "Unit Price", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblOrders);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 700, 170));

        btnPurhchaseOrder.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnPurhchaseOrder.setText("Purchase");
        btnPurhchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurhchaseOrderActionPerformed(evt);
            }
        });
        jPanel6.add(btnPurhchaseOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 110, 30));

        lblGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGrandTotal.setText("0.00");
        jPanel6.add(lblGrandTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 192, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("TOTAL :");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 192, -1, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 720, 230));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCusNameActionPerformed

    private void txtSearcCusNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearcCusNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearcCusNoActionPerformed

    private void btnAddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTableActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblOrders.getModel();
        String itmCode = txtItemCode.getText();
        String itmName = txtItemName.getText();
        int qty = Integer.parseInt(txtBuyQty.getText());
        double price = Double.parseDouble(txtUnitPrice.getText());
        double total = price * qty;

        int currentRow = checkItem(itmCode);
        if (currentRow == -1) {
            Object[] row = {itmCode, itmName, qty, price, total};
            dtm.addRow(row);
        } else {
            qty += Integer.parseInt(dtm.getValueAt(currentRow, 2).toString());
            total = price * qty;
            tblOrders.setValueAt(qty, currentRow, 2);
            tblOrders.setValueAt(total, currentRow, 4);
        }

        getGrandTotal();

    }//GEN-LAST:event_btnAddTableActionPerformed

    private void btnPurhchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurhchaseOrderActionPerformed
        try {
            String oId = txtOID.getText();
            String oDate = txtODate.getText();
            String cusId = txtSearcCusNo.getText();
            double fullTotal = Double.parseDouble(lblGrandTotal.getText());

            OrderDTO o = new OrderDTO(oId, oDate, cusId, fullTotal);

            ArrayList<OrderDetailDTO> odList = new ArrayList<>();
            for (int i = 0; i < dtm.getRowCount(); i++) {
                String itmCode = dtm.getValueAt(i, 0).toString();
                int qty = Integer.parseInt(dtm.getValueAt(i, 2).toString());
                double price = Double.parseDouble(dtm.getValueAt(i, 3).toString());

                OrderDetailDTO od = new OrderDetailDTO(oId, itmCode, qty, price);
                odList.add(od);
            }

            boolean added = new OrderController().placeOrder(o);
            if (added) {
                JOptionPane.showMessageDialog(rootPane, "Placed!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Not Placed!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPurhchaseOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String cusno = txtSearcCusNo.getText();
            CustomerDTO cus = new OrderController().searchCustomer(cusno);
            if (cus != null) {
                txtSearcCusNo.setText(String.valueOf(cus.getContactNumber()));
                txtCusName.setText(cus.getName());
                txtCusAddress.setText(cus.getAddress());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Not found!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbItemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbItemItemStateChanged
        try {
            String g = cmbItem.getSelectedItem().toString();
            ItemDTO itm = new OrderController().searchItem(g);

            txtItemCode.setText(itm.getItemCode());
            txtItemName.setText(itm.getDesc());
            txtItemQtyOnHand.setText(String.valueOf(itm.getQty()));
            txtUnitPrice.setText(String.valueOf(itm.getPrice()));
            
            

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbItemItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
        new Menu().show();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTable;
    private javax.swing.JButton btnPurhchaseOrder;
    private javax.swing.JComboBox<String> cmbItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JTable tblOrders;
    private javax.swing.JTextField txtBuyQty;
    private javax.swing.JTextField txtCusAddress;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemQtyOnHand;
    private javax.swing.JTextField txtODate;
    private javax.swing.JTextField txtOID;
    private javax.swing.JTextField txtSearcCusNo;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables

    private void loadAllItems() {
        try {
            ArrayList<ItemDTO> loadAllItems = new OrderController().loadAllItems();
            for (ItemDTO itm : loadAllItems) {
                cmbItem.addItem(itm.getItemCode());
            }
        } catch (SQLException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(OrderForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setDate() {
        String date = LocalDate.now().toString();
        txtODate.setText(date);
    }

    private int checkItem(String itmCode) {
        DefaultTableModel dtm = (DefaultTableModel) tblOrders.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            String t = tblOrders.getValueAt(i, 0).toString();
            if (t.equalsIgnoreCase(itmCode)) {
                return i;
            }
        }
        return -1;
    }

    private void getGrandTotal() {
        double total = 0;
        for (int i = 0; i < tblOrders.getRowCount(); i++) {
            total += Double.parseDouble(tblOrders.getValueAt(i, 4).toString());
        }

        lblGrandTotal.setText(String.valueOf(total));
    }
}
